title: Tina Boyce
author: Tina Boyce
description: >
  Tina Boyce's GitHub page. Current under construction...
twitter_username: elegantpoem
github_username:  tinaboyce

# Build settings
markdown: kramdown
theme: minima
